// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFv4lcxWTD407U1uqmgNcfFi40_T3taqg',
    appId: '1:419229901848:web:7fee8e702ef3ce3da44f6d',
    messagingSenderId: '419229901848',
    projectId: 'btchat-9ec76',
    authDomain: 'btchat-9ec76.firebaseapp.com',
    storageBucket: 'btchat-9ec76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCARmtZCORp257bgf4LHt6UIInQr692HnE',
    appId: '1:419229901848:android:910d7dbe9a366f5ea44f6d',
    messagingSenderId: '419229901848',
    projectId: 'btchat-9ec76',
    storageBucket: 'btchat-9ec76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdDeNhR0cC-ws4fZvUJ6haIeSr_O9Vr5A',
    appId: '1:419229901848:ios:bc5c0a2629d4659aa44f6d',
    messagingSenderId: '419229901848',
    projectId: 'btchat-9ec76',
    storageBucket: 'btchat-9ec76.appspot.com',
    iosClientId: '419229901848-7ctuaq2vlf7v7fc74m2ouj4fjr5i839b.apps.googleusercontent.com',
    iosBundleId: 'com.example.btchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdDeNhR0cC-ws4fZvUJ6haIeSr_O9Vr5A',
    appId: '1:419229901848:ios:edc60c57a68bbf82a44f6d',
    messagingSenderId: '419229901848',
    projectId: 'btchat-9ec76',
    storageBucket: 'btchat-9ec76.appspot.com',
    iosClientId: '419229901848-cqj3bt7i05au2g858jf163o4d82u91h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.btchat.RunnerTests',
  );
}
